# ============================================================
# Script:   app_config.R
# Purpose:  One place for the values that decide how the app looks:
#           typography, sidebar and box geometry, and the stylesheet
#           built from them.
# Exports:  app_config (list), build_app_css()
# Note:     Sizes are px, not rem. Bootstrap 3 sets html{font-size:10px},
#           so rem values tuned against a 16px root render smaller than
#           body text and invert the heading hierarchy.
# ============================================================
# Sections:
#   build_app_css()
# ============================================================


app_config <- list(
  data_dir = "data",
  sidebar_width = 230L,
  file_map = c(
    "CRISPR (23Q4)" = "CRISPRGeneEffect_23Q4_clean.rds",
    "RNAi" = "d2_gene_effect_headers_refined.rds"
  ),
  # Plain-text subtype lists for the Cancer Dependencies picker (one line per OncotreeSubtype).
  # Regenerated by docs/scripts/preprocess_data.R when model + gene-effect RDS exist.
  cancer_subtype_list_files = c(
    "CRISPR (23Q4)" = "cancer_subtypes_CRISPR.txt",
    "RNAi" = "cancer_subtypes_RNAi.txt"
  ),
  ui = list(
    body_scale = 1,
    home_scale = 1.1,
    title_scale = 1,
    # Every size here was 18px and every heading 1.8rem, which reads as a
    # presentation slide rather than a working tool and leaves no hierarchy
    # between a section title and the body under it. Tables carry the most
    # information per row, so they run a size smaller again.
    base_font_px = 15,
    sidebar_font_px = 15,
    tab_font_px = 14,
    input_font_px = 14,
    box_body_font_px = 14,
    table_font_px = 13,
    # Headings in px, not rem: Bootstrap 3 sets the root font size to 10px, so
    # rem values tuned against a 16px root render every heading smaller than
    # the body text under it.
    h2_px = 24,
    h3_px = 20,
    h4_px = 17,
    h5_px = 15,
    swiss_h4_px = 17,
    swiss_h5_px = 15,
    box_title_px = 15,
    brand_font_px = 19
  ),
  plot_theme = list(
    base_size = 13,
    title_size = 15,
    subtitle_size = 12,
    axis_title_size = 12,
    legend_title_size = 14,
    legend_text_size = 13
  ),
  # Usage logs: set CPT_LOG_USAGE=1 to append JSON Lines under logs/usage/ (see docs/LOGGING.md)
  logging = list(
    enabled = FALSE,
    dir = "logs/usage"
  )
)

build_app_css <- function(cfg = app_config$ui) {
  body_scale <- cfg$body_scale
  home_scale <- cfg$home_scale
  title_scale <- cfg$title_scale
  px <- function(v, s = body_scale) sprintf("%.2fpx", v * s)

  paste0(
    "body .wrapper, .content-wrapper, .right-side { font-size: ", px(cfg$base_font_px), "; }",
    ".main-sidebar .sidebar-menu a { font-size: ", px(cfg$sidebar_font_px), "; }",
    ".nav-tabs > li > a, .nav-pills > li > a { font-size: ", px(cfg$tab_font_px), " !important; padding: 10px 16px !important; }",
    ".box-body { font-size: ", px(cfg$box_body_font_px), "; }",
    ".box-body p, .box-body li, .box-body label, .box-body .help-block, .form-control, .selectize-input, .selectize-dropdown, .btn, .control-label, .radio, .checkbox { font-size: ", px(cfg$input_font_px), " !important; }",
    "h2 { font-size: ", px(cfg$h2_px * home_scale), "; }",
    ".cpt-home-hero h2, .cpt-home-hero p { font-size: ", px(cfg$h2_px * home_scale), " !important; }",
    ".swissadme-explorer-pane h4 { font-size: ", px(cfg$swiss_h4_px * title_scale), "; }",
    ".swissadme-explorer-pane h5 { font-size: ", px(cfg$swiss_h5_px * title_scale), "; }",
    "h3, .h3 { font-size: ", px(cfg$h3_px * title_scale), "; }",
    "h4, .h4, .box-body h4 { font-size: ", px(cfg$h4_px * title_scale), "; font-weight: 600; }",
    "h5 { font-size: ", px(cfg$h5_px * title_scale), "; font-weight: 600; }",
    ".dataTables_wrapper, table.dataTable { font-size: ", px(cfg$table_font_px), " !important; }",
    ".content-wrapper, .right-side { background-color: #ecf0f5; }",
    ".box-header .box-title { font-weight: 400 !important; font-size: ", px(cfg$box_title_px, title_scale), " !important; }",
    ".box.box-solid.box-info > .box-header { background-color: #478EB8 !important; background-image: none !important; color: #FFFFFF !important; }",
    ".box.box-solid.box-info > .box-header .box-title { color: #FFFFFF !important; font-weight: 400 !important; font-size: ", px(cfg$box_title_px, title_scale), " !important; }",
    ".box.box-solid.box-primary > .box-header { background-color: #478EB8 !important; background-image: none !important; color: #FFFFFF !important; }",
    ".box.box-solid.box-primary > .box-header .box-title { color: #FFFFFF !important; font-weight: 400 !important; font-size: ", px(cfg$box_title_px, title_scale), " !important; }",
    ".box.box-solid.box-primary { border-color: #478EB8 !important; border-top-color: #478EB8 !important; }",
    ".box.box-solid.box-info { border-color: #478EB8 !important; border-top-color: #478EB8 !important; }",
    ".cpt-status-banner { padding: 10px 14px; border-radius: 6px; border: 1px solid; font-weight: 600; }",
    ".cpt-status-info { background:#eaf4ff; border-color:#b7d7f2; color:#1f5e8c; }",
    ".cpt-status-warning { background:#fff8e6; border-color:#f0cf75; color:#8a6d1b; }",
    ".shiny-notification { font-size: 20px !important; font-weight: 600; padding: 16px 20px !important; border-radius: 8px !important; box-shadow: 0 4px 14px rgba(0,0,0,0.2); }",
    ".shiny-notification-message { background-color: #eaf4ff !important; border: 2px solid #478EB8 !important; color: #1f5e8c !important; }",
    ".shiny-notification-warning { background-color: #fff7e6 !important; border: 2px solid #e0a800 !important; color: #7a5600 !important; }",
    ".shiny-notification-error { background-color: #ffe9ea !important; border: 2px solid #cc3340 !important; color: #8b1f27 !important; }",
    ".skin-blue .main-header .logo, .skin-blue .main-header .navbar { background-color: #478EB8 !important; }",
    ".main-header .logo, .main-header .navbar { height: 56px !important; min-height: 56px !important; line-height: 56px !important; }",
    ".main-header .logo { display: flex !important; align-items: center; justify-content: center; padding: 0 12px !important; }",
    ".main-header .navbar .sidebar-toggle { height: 56px !important; width: 56px !important; padding: 0 !important; display: flex !important; align-items: center; justify-content: center; }",
    ".main-header .navbar .sidebar-toggle:before { line-height: 1 !important; }",
    ".main-header .logo { font-size: ", px(cfg$brand_font_px), " !important; font-weight: 400 !important; line-height: 1.2; }",
    ".main-header .navbar .navbar-brand { font-size: ", px(cfg$brand_font_px), " !important; font-weight: 400 !important; }",
    ".main-header .navbar .navbar-brand span { font-size: ", px(cfg$brand_font_px), " !important; font-weight: 400 !important; }",
    ".main-header .navbar-nav > li > #share_view { background: rgba(255,255,255,0.15) !important; border: 1px solid rgba(255,255,255,0.3) !important; color: #fff !important; border-radius: 4px; padding: 6px 12px; margin: 12px 10px; font-size: 13px; cursor: pointer; transition: background 0.2s; }",
    ".main-header .navbar-nav > li > #share_view:hover { background: rgba(255,255,255,0.3) !important; }",

    # ---- ui_kit.R components (collapsible help, notes, empty states) ----
    # Explanatory text is collapsed by default so results lead; one click reveals it.
    ".cpt-help { display: inline-block; vertical-align: middle; margin-left: 6px; }",
    ".cpt-help > summary { list-style: none; cursor: pointer; display: inline-flex; align-items: center; gap: 4px; color: #478EB8; font-weight: 400; }",
    ".cpt-help > summary::-webkit-details-marker { display: none; }",
    ".cpt-help > summary:hover { color: #1a3a5c; }",
    ".cpt-help[open] > summary { color: #1a3a5c; }",
    ".cpt-help-label { font-size: ", px(11), "; }",
    ".cpt-help-body { font-size: ", px(11), " !important; font-weight: 400; line-height: 1.5; color: #33506b; background: #f5faff; border-left: 3px solid #478EB8; border-radius: 0 4px 4px 0; padding: 8px 10px; margin: 6px 0 2px; max-width: 560px; }",
    ".cpt-note { border-radius: 4px; margin: 4px 0 10px; }",
    ".cpt-note > summary { cursor: pointer; list-style: none; font-size: ", px(11), " !important; font-weight: 600; padding: 6px 8px; }",
    ".cpt-note > summary::-webkit-details-marker { display: none; }",
    ".cpt-note > summary:before { content: '\\f05a'; font-family: 'Font Awesome 6 Free', 'Font Awesome 5 Free', FontAwesome; font-weight: 900; margin-right: 6px; opacity: 0.8; }",
    ".cpt-note-body { font-size: ", px(11), " !important; font-weight: 400; line-height: 1.5; padding: 0 8px 8px 8px; }",
    ".cpt-note-caution { background: #fcf8e3; border-left: 3px solid #e0a800; color: #8a6d3b; }",
    ".cpt-note-info { background: #eef5fb; border-left: 3px solid #478EB8; color: #1f5e8c; }",
    ".cpt-section-title { display: flex; align-items: center; }",
    ".cpt-empty-state { padding: 14px 16px; border-radius: 6px; background: #f7f9fb; border: 1px dashed #c3d4e2; color: #45637c; display: flex; align-items: center; gap: 8px; }",

    # ---- Gene tab: cysteine tiers --------------------------------------
    # Tier 1 functional+ligandable, 2 functional only, 3 ligandable only,
    # 4 tested/neither. Colour carries the ranking so the table does not
    # have to be read to see where a gene sits.
    ".cpt-gene-header { display: flex; align-items: baseline; gap: 12px; margin: 0 0 10px 2px; }",
    ".cpt-gene-header h2 { margin: 0; font-weight: 600; color: #1a3a5c; }",
    ".cpt-tier { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: ", px(11), "; font-weight: 600; }",
    ".cpt-tier-1 { background: #e6f4ec; color: #1d5c3f; border: 1px solid #a8d5bd; }",
    ".cpt-tier-2 { background: #eaf4ff; color: #1f5e8c; border: 1px solid #b7d7f2; }",
    ".cpt-tier-3 { background: #fff8e6; color: #8a6d1b; border: 1px solid #f0cf75; }",
    ".cpt-tier-4 { background: #f2f2f2; color: #555555; border: 1px solid #d8d8d8; }",
    ".cpt-tier-na { background: #f2f2f2; color: #777777; border: 1px solid #e0e0e0; }",
    ".cpt-tier-row { display: flex; flex-wrap: wrap; gap: 10px; margin: 4px 0 2px; }",
    ".cpt-tier-chip { display: flex; align-items: center; gap: 8px; padding: 8px 12px; border-radius: 6px; min-width: 200px; }",
    ".cpt-tier-chip.cpt-tier-1 { background: #e6f4ec; border: 1px solid #a8d5bd; }",
    ".cpt-tier-chip.cpt-tier-2 { background: #eaf4ff; border: 1px solid #b7d7f2; }",
    ".cpt-tier-chip.cpt-tier-3 { background: #fff8e6; border: 1px solid #f0cf75; }",
    ".cpt-tier-chip.cpt-tier-4 { background: #f2f2f2; border: 1px solid #d8d8d8; }",
    ".cpt-tier-count { font-size: ", px(20), "; font-weight: 700; min-width: 24px; text-align: right; }",
    ".cpt-tier-label { font-size: ", px(11), "; line-height: 1.3; }",
    ".cpt-collapse-block > summary { cursor: pointer; list-style: none; font-weight: 600; color: #478EB8; padding: 4px 0; }",
    ".cpt-collapse-block > summary::-webkit-details-marker { display: none; }",
    ".cpt-collapse-block > summary:hover { color: #1a3a5c; }",
    ".cpt-collapse-body { padding-top: 10px; }",

    # ---- Home entry points ---------------------------------------------
    ".cpt-home-entries { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 12px; margin: 22px 0 26px; text-align: left; }",
    ".cpt-entry { display: block; background: #fff; border: 1px solid #dbe5ec; border-radius: 6px; padding: 14px 16px; color: #1a3a5c !important; text-decoration: none !important; transition: border-color 0.15s, box-shadow 0.15s; }",
    ".cpt-entry:hover, .cpt-entry:focus { border-color: #478EB8; box-shadow: 0 2px 8px rgba(71,142,184,0.18); color: #1a3a5c !important; }",
    ".cpt-entry-icon { color: #478EB8; margin-right: 8px; }",
    ".cpt-entry-title { font-weight: 600; font-size: ", px(15), "; }",
    ".cpt-entry-q { display: block; margin-top: 5px; color: #5d6b76; font-size: ", px(12), "; line-height: 1.4; }",

    # ---- Discover: evidence funnel -------------------------------------
    # Counts surviving each enabled layer, in the manuscript's order.
    ".cpt-funnel { display: flex; flex-wrap: wrap; gap: 10px; margin: 4px 0 14px; }",
    ".cpt-funnel-step { flex: 1 1 170px; background: #fff; border: 1px solid #dbe5ec; border-left: 4px solid #478EB8; border-radius: 4px; padding: 10px 14px; }",
    ".cpt-funnel-n { display: block; font-size: ", px(22), "; font-weight: 700; color: #1a3a5c; line-height: 1.1; }",
    ".cpt-funnel-label { display: block; margin-top: 3px; font-size: ", px(11), "; color: #5d6b76; }",

    # ---- Discover: gene drawer -----------------------------------------
    # Opens over the right edge on row click rather than taking a permanent
    # column: the candidate table already scrolls horizontally.
    ".cpt-drawer { position: fixed; top: 56px; right: 0; width: 380px; max-width: 92vw; height: calc(100vh - 56px); background: #fff; border-left: 1px solid #cfdae2; box-shadow: -4px 0 18px rgba(26,58,92,0.13); z-index: 1040; display: flex; flex-direction: column; }",
    ".cpt-drawer-head { display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 10px 14px; border-bottom: 1px solid #e7edf1; background: #f7fafc; }",
    ".cpt-drawer-open { font-size: ", px(12), "; font-weight: 600; }",
    ".cpt-drawer-close { color: #6b7d88 !important; font-size: ", px(15), "; }",
    ".cpt-drawer-close:hover { color: #1a3a5c !important; }",
    ".cpt-drawer-body { padding: 14px 16px 24px; overflow-y: auto; }",
    ".cpt-drawer-body .cpt-gene-header h2 { font-size: ", px(21), " !important; }",
    ".cpt-card-stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; margin: 12px 0 16px; }",
    ".cpt-card-stat { background: #f2f7fa; border-radius: 4px; padding: 8px 6px; text-align: center; }",
    ".cpt-card-stat-n { display: block; font-size: ", px(17), "; font-weight: 700; color: #1a3a5c; }",
    ".cpt-card-stat-l { display: block; font-size: ", px(10), "; color: #5d6b76; }",
    ".cpt-card-h { margin: 16px 0 6px !important; font-size: ", px(12), " !important; text-transform: uppercase; letter-spacing: 0.06em; color: #5d6b76 !important; }",
    ".cpt-card-rows { display: flex; flex-direction: column; }",
    ".cpt-card-row { display: flex; justify-content: space-between; gap: 10px; padding: 5px 0; border-bottom: 1px solid #eef2f5; font-size: ", px(12), "; }",
    ".cpt-card-row-l { color: #26414f; }",
    ".cpt-card-row-r { font-variant-numeric: tabular-nums; color: #1a3a5c; font-weight: 600; }",

    # ---- Target tab: two-subtype comparison -----------------------------
    ".cpt-cmp-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 12px; margin-top: 10px; }",
    ".cpt-cmp-col { background: #f7fafc; border: 1px solid #dbe5ec; border-radius: 4px; padding: 12px 14px; }",
    ".cpt-cmp-name { font-weight: 700; color: #1a3a5c; margin-bottom: 8px; font-size: ", px(13), "; }",
    ".cpt-cmp-row { display: flex; justify-content: space-between; gap: 12px; padding: 4px 0; font-size: ", px(12), "; color: #45637c; }",
    ".cpt-cmp-row b { font-variant-numeric: tabular-nums; color: #1a3a5c; }",
    ".cpt-cmp-stat { border-top: 1px solid #e7edf1; }",

    # ---- Compact control panels -----------------------------------------
    # The app-wide input size (18px) is right for reading results and far too
    # heavy for a wall of filters, so the control blocks step down a size and
    # tighten their spacing.
    ".cpt-controls .box { margin-bottom: 12px; }",
    ".cpt-controls .box-body { padding: 10px 14px 12px; }",
    ".cpt-controls .form-group { margin-bottom: 10px; }",
    ".cpt-controls .checkbox, .cpt-controls .radio { margin: 3px 0; }",
    ".cpt-controls .checkbox label, .cpt-controls .radio label, .cpt-controls .form-control, .cpt-controls .btn { font-size: ", px(13.5), " !important; line-height: 1.35; }",
    ".cpt-controls .form-control { height: auto; padding: 5px 9px; }",
    ".cpt-controls textarea.form-control { min-height: 52px; }",
    ".cpt-controls hr { margin: 10px 0; }",
    ".cpt-field-label { display: block; font-size: ", px(12.5), " !important; font-weight: 700; color: #33506b; margin: 2px 0 5px; }",
    ".cpt-field-label .cpt-help { margin-left: 5px; }",
    # Equal-height control boxes: the three layers should read as one row of
    # peers, not three blocks of whatever height their contents happen to make.
    ".cpt-controls > .row { display: flex; flex-wrap: wrap; align-items: stretch; }",
    ".cpt-controls > .row > div[class*='col-'] { display: flex; }",
    ".cpt-controls > .row > div[class*='col-'] > .box { width: 100%; display: flex; flex-direction: column; margin-bottom: 12px; }",
    ".cpt-controls > .row > div[class*='col-'] > .box > .box-body { flex: 1 1 auto; }",
    # The query bar is the page's primary control: what evidence, what a row
    # means, and go. It should outweigh the parameter boxes above it.
    ".cpt-action-bar { display: flex; align-items: flex-end; justify-content: space-between; gap: 18px; flex-wrap: wrap; background: #eef5fb; border: 1px solid #b7d7f2; border-left: 4px solid #478EB8; border-radius: 4px; padding: 12px 16px; margin: 0 15px 16px; box-shadow: 0 1px 4px rgba(26,58,92,0.07); }",
    ".cpt-action-grain .radio-inline { margin-right: 14px; font-size: ", px(13), " !important; }",
    ".cpt-action-bar .btn { font-size: ", px(13.5), " !important; padding: 7px 18px; }",
    ".cpt-scope-note { font-size: ", px(12.5), "; color: #45637c; background: #f5faff; border-left: 3px solid #478EB8; padding: 7px 10px; margin: 0 0 10px; }",
    ".cpt-box-summary { font-size: ", px(12.5), "; color: #1a3a5c; font-weight: 600; line-height: 1.45; }",
    ".cpt-box-details { margin-top: 0; }",
    ".cpt-box-details > summary { cursor: pointer; list-style: none; font-size: ", px(11.5), "; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; color: #478EB8; padding: 3px 0; }",
    ".cpt-box-details > summary::-webkit-details-marker { display: none; }",
    ".cpt-box-details > summary:before { content: '\\f013'; font-family: 'Font Awesome 6 Free', 'Font Awesome 5 Free', FontAwesome; font-weight: 900; margin-right: 6px; }",
    ".cpt-box-details[open] > summary { color: #1a3a5c; }",
    # display:flex only — width must stay with the Bootstrap column class, or
    # the three boxes lose their grid and stack.
    ".cpt-layer-box { display: flex; }",
    # box(width = 12) wraps the .box in a col-sm-12 div, so the chain has to go
    # through it — a ".cpt-layer-box > .box" selector matches nothing.
    ".cpt-layer-box > .col-sm-12 { display: flex; width: 100%; padding-left: 0; padding-right: 0; }",
    ".cpt-layer-box > .col-sm-12 > .box { width: 100%; margin-bottom: 0; display: flex; flex-direction: column; }",
    # The body is a flex column so the browse button's margin-top:auto pins it
    # to the foot of the box; the three boxes are equal height, so the buttons
    # land on one baseline instead of floating at whatever height the controls
    # above them happen to end.
    ".cpt-layer-box > .col-sm-12 > .box > .box-body { display: flex; flex-direction: column; flex: 1 1 auto; gap: 10px; }",
    ".cpt-controls > .row { margin-bottom: 12px; }",
    # Applied to the column itself: a child selector loses to AdminLTE's own
    # !important header rule, which is more specific than anything sane here.
    ".cpt-layer-box.cpt-box-off { opacity: 0.5; filter: saturate(0.4); }",
    # Dimmed while another layer is being browsed: the controls still work, but
    # they do not govern what is on screen, so they should not compete with it.
    # ---- Stat tiles -------------------------------------------------
    # Three tabs drew these three different ways: Target had one blue tile and
    # three black ones, the atlas had blue/cyan/green/red, Discover had a blue
    # ramp. Four hues on four numbers implies four kinds of thing, when they
    # are all just counts. Every tile is now the same neutral card whatever
    # colour class the module passed, and emphasis is carried by exactly one
    # filled tile (.bg-navy) rather than by hue.
    ".small-box { background: #ffffff !important; color: #1a3a5c !important;",
    "  border: 1px solid #dde5ea; border-top: 3px solid #478EB8;",
    "  border-radius: 3px; box-shadow: none; min-height: 92px; }",
    ".small-box h3 { color: #1a3a5c !important; font-weight: 700; font-size: ", px(30), "; margin: 2px 0 0 0; }",
    ".small-box p { color: #5b6b76 !important; font-size: ", px(12.5), "; font-weight: 600; margin: 0; }",
    # shinydashboard positions the icon absolutely at ~70px, sized for its own
    # taller card. On this flatter tile it overflowed the right edge and sat at
    # a different height in every box. Pin it centred, clipped and one size.
    ".small-box { position: relative; overflow: hidden; }",
    # The wrapper shinydashboard emits is .icon-large and the glyph is .fas,
    # not .fa — a rule written for .fa silently misses every icon.
    ".small-box .icon, .small-box .icon-large, .small-box .icon-large > i,",
    ".small-box i.fa, .small-box i.fas, .small-box svg {",
    "  color: #478EB8 !important; opacity: 0.14;",
    "  position: absolute; top: 50%; right: 16px; left: auto; bottom: auto;",
    "  transform: translateY(-50%);",
    "  font-size: 40px !important; width: 40px; height: 40px; line-height: 1; }",
    ".small-box > .inner { position: relative; z-index: 1; padding-right: 58px; }",
    ".small-box:hover { border-color: #478EB8; }",
    # The single emphasised tile: the number the rest of the row builds up to.
    ".small-box.bg-navy { background: #1a3a5c !important; border-color: #1a3a5c; }",
    ".small-box.bg-navy h3, .small-box.bg-navy p { color: #ffffff !important; }",
    ".small-box.bg-navy .icon, .small-box.bg-navy .icon-large, .small-box.bg-navy .icon-large > i, .small-box.bg-navy i.fas, .small-box.bg-navy svg { color: #ffffff !important; opacity: 0.22; }",
    ".small-box .small-box-footer { display: none; }",

    # ---- Second-level navigation -------------------------------------
    # Tabs inside tabs read as one broken row of tabs: same shape, same
    # weight, no signal about which level you are on. The outer level stays
    # tabs; every nested level becomes a segmented pill control, which is the
    # conventional way to say "these are views of what the tab already chose".
    ".tab-pane .nav-tabs { border-bottom: none; display: inline-flex; flex-wrap: wrap;",
    "  background: #eef3f7; border: 1px solid #dde5ea; border-radius: 5px; padding: 3px; gap: 2px; margin-bottom: 14px; }",
    ".tab-pane .nav-tabs > li { float: none; margin: 0; }",
    ".tab-pane .nav-tabs > li > a { border: none !important; border-radius: 4px; margin: 0;",
    "  padding: 5px 14px; font-size: ", px(12.5), "; font-weight: 600; color: #47607a; background: transparent !important; }",
    ".tab-pane .nav-tabs > li > a:hover { color: #1a3a5c; background: #e2eaf1 !important; }",
    ".tab-pane .nav-tabs > li.active > a, .tab-pane .nav-tabs > li.active > a:hover {",
    "  background: #ffffff !important; color: #1a3a5c !important; box-shadow: 0 1px 2px rgba(26,58,92,0.16); }",
    # Chart switchers use the same pill language as nested tabs.
    ".btn-cpt-seg { background: transparent; border: none; color: #47607a; font-weight: 600;",
    "  font-size: ", px(12.5), "; padding: 5px 14px; border-radius: 4px; box-shadow: none; }",
    ".btn-cpt-seg.active, .btn-cpt-seg:active { background: #ffffff !important; color: #1a3a5c !important;",
    "  box-shadow: 0 1px 2px rgba(26,58,92,0.16) !important; }",
    ".btn-cpt-seg:hover { background: #e2eaf1; color: #1a3a5c; }",
    ".btn-group-container-sw:has(.btn-cpt-seg), .btn-group:has(.btn-cpt-seg) {",
    "  background: #eef3f7; border: 1px solid #dde5ea; border-radius: 5px; padding: 3px; margin-bottom: 12px; }",

    # Grouped switcher. With every layer on there are nine tables, and one
    # unbroken strip of them reads as a single undifferentiated list. One row
    # per kind -- the summary, then each layer on its own, then the joins --
    # so the shape of the evidence is visible before anything is clicked.
    # DT sizes each column filter to its column, so a narrow column such as
    # Gene gives a box a few characters wide and what you type scrolls out of
    # sight as you type it. Let the box fill its cell, keep a floor under it,
    # and widen it while it has focus so a long value stays readable.
    "table.dataTable thead input[type=\"search\"],",
    "table.dataTable thead input[type=\"text\"] {",
    "  width: 100% !important; min-width: 74px; box-sizing: border-box;",
    "  font-size: ", px(12), "; padding: 4px 7px; height: auto;",
    "  border: 1px solid #cfd8de; border-radius: 3px;",
    "  transition: box-shadow .12s ease, border-color .12s ease; }",
    "table.dataTable thead input:focus {",
    "  border-color: #478EB8; outline: none;",
    "  box-shadow: 0 0 0 2px rgba(71,142,184,0.18);",
    "  position: relative; z-index: 3; min-width: 190px; }",
    # The filter row sits in its own header row; give it a little breathing
    # space so the boxes do not touch the column titles above them.
    "table.dataTable thead tr:nth-child(2) th,",
    "table.dataTable thead tr:nth-child(2) td { padding: 4px 6px 8px; }",

    ".cpt-switch { margin-bottom: 12px; }",
    ".cpt-switch-row { display: flex; flex-wrap: wrap; align-items: center; gap: 3px;",
    "  background: #eef3f7; border: 1px solid #dde5ea; border-radius: 5px;",
    "  padding: 3px; margin-bottom: 6px; }",
    ".cpt-switch-row:last-child { margin-bottom: 0; }",
    ".cpt-switch-tag { font-size: ", px(11), "; font-weight: 700; letter-spacing: 0.04em;",
    "  text-transform: uppercase; color: #7b8a94; padding: 0 10px 0 6px; white-space: nowrap; }",
    ".cpt-switch-btn { background: transparent; border: none; color: #47607a; font-weight: 600;",
    "  font-size: ", px(12.5), "; padding: 5px 14px; border-radius: 4px; box-shadow: none; }",
    ".cpt-switch-btn:hover { background: #e2eaf1; color: #1a3a5c; }",
    ".cpt-switch-btn.active { background: #ffffff; color: #1a3a5c;",
    "  box-shadow: 0 1px 2px rgba(26,58,92,0.16); }",

    # ---- Narrow viewports --------------------------------------------
    # col-sm-* keeps its grid all the way down to 768px, so on a tablet the
    # three control boxes sat side by side at 179px each and the four stat
    # tiles at 105px — "30,219 engaged cysteine records" in 105px. Nothing
    # overflowed; they were simply too narrow to read. Stack them instead.
    "@media (max-width: 991px) {",
    "  .cpt-layer-box { width: 100% !important; margin-bottom: 12px; }",
    "  .col-sm-3:has(.small-box) { width: 50%; }",
    "  .cpt-action-grid { display: block; }",
    "}",
    "@media (max-width: 600px) {",
    "  .col-sm-3:has(.small-box) { width: 100%; }",
    "}",
    # A long label should wrap, not be cut off mid-word. All three browse
    # long labels clip at tablet width otherwise.

    # ---- Plot containment --------------------------------------------
    # plotly sizes itself from the container it is measured in; inside a box
    # that has padding it would overrun onto the page background. Clipping the
    # box and letting the widget fill it keeps the chart inside its card.
    # Do NOT put overflow:hidden on .box — selectize dropdowns inside the
    # layer boxes overflow their box by design and would be clipped. Constrain
    # the widget instead; the real overhang fix is the resize observer in
    # cpt_plotly(), which re-measures a chart drawn while its panel was hidden.
    ".box-body > .html-widget, .box-body .js-plotly-plot { width: 100% !important; max-width: 100%; }",
    ".box-body .plotly .main-svg { max-width: 100%; }",
    ".tab-content { overflow-x: auto; }",

    ".cpt-box-dim { opacity: 0.42; filter: saturate(0.35); transition: opacity 0.15s ease; }",
    # Wide tables and plots scroll inside their own box instead of pushing the
    # page sideways.
    ".cpt-scroll-x { overflow-x: auto; max-width: 100%; }",
    ".box-body { overflow-x: auto; }",
    ".cpt-layer-box > .col-sm-12 > .box > .box-body { overflow-x: visible; }",
    ".dataTables_wrapper { overflow-x: auto; }",
    ".js-plotly-plot, .plotly, .html-widget { max-width: 100%; }",
    ".cpt-layer-box.cpt-box-off .box-header .box-title:after { content: ' — layer off'; font-size: 0.8em; opacity: 0.9; }",
    ".cpt-run-hint { font-size: ", px(11), " !important; margin: 6px 0 0; }",
    # One baseline row: layers, gene list, grain, action — so "Restrict to genes"
    # lines up with the layer checkboxes instead of floating above them.
    ".cpt-action-grid { display: grid !important; grid-template-columns: auto 1fr auto; grid-template-areas: 'layers genes action' 'grain grain action' 'weights weights weights'; gap: 10px 20px; align-items: start; }",
    ".cpt-action-grid > div:nth-child(1) { grid-area: layers; }",
    ".cpt-action-grid > div:nth-child(2) { grid-area: genes; }",
    ".cpt-action-grid > div:nth-child(3) { grid-area: grain; }",
    ".cpt-action-grid > div:nth-child(4) { grid-area: weights; }",
    ".cpt-action-weights { border-top: 1px solid #cfe2f3; padding-top: 8px; }",
    ".cpt-section-anchor { position: relative; top: -70px; height: 0; }",
    ".cpt-browse-btn { margin-bottom: 8px; font-weight: 600; border-color: #b7d7f2; color: #1f5e8c; }",
    ".cpt-browse-btn:hover { background: #eef5fb; border-color: #478EB8; color: #1a3a5c; }",
    ".cpt-browse-btn { white-space: normal; line-height: 1.3; }",
    ".cpt-run-stale { margin: 6px 0 0; font-size: 12px; color: #8a6d3b; text-align: right; max-width: 320px; }",
    ".cpt-guide { max-width: 760px; padding: 4px 4px 12px; }",
    ".cpt-guide p { margin-bottom: 12px; line-height: 1.6; }",
    ".cpt-guide ul { margin-bottom: 14px; padding-left: 20px; }",
    ".cpt-guide li { margin-bottom: 7px; line-height: 1.55; }",
    ".cpt-guide .cpt-section-title { margin-top: 20px; }",
    ".cpt-guide > .cpt-section-title:first-child { margin-top: 4px; }",
    ".cpt-action-weights .form-group { margin-bottom: 4px; }",
    ".cpt-action-weights .irs { margin-bottom: 0; }",
    ".cpt-action-grid > .cpt-action-run { grid-area: action; align-self: center; justify-self: end; display: flex; gap: 8px; }",
    ".cpt-action-grid .form-group { margin-bottom: 0; }",
    ".cpt-action-genes { min-width: 210px; }",
    ".cpt-action-genes textarea { resize: vertical; }",
    ".cpt-atlas-block { margin-top: 4px; }",
    ".cpt-atlas-block > summary { font-size: ", px(14), "; }"
  )
}
